#
# Automatically generated by 'make config' -- don't edit!
#
CONFIG_ARCH=amd64
CONFIG_SOURCE_ROOT=.
CONFIG_WWW_ROOT=.

CONFIG_BUILD_NO=100
CONFIG_VERSION_MAJOR=2
CONFIG_VERSION_MINOR=10
CONFIG_REVISION_NO=1

BUILD_RELEASE=0

CONFIG_OEM=ProphetStor
CONFIG_LICENSE_OEM=ProphetStor
CONFIG_VENDOR=ProphetStor_Data_Services
CONFIG_VENDOR_SHORT=ProphetStor
CONFIG_VENDOR_LOW=prophetstor
CONFIG_VENDOR_DISPLAY="ProphetStor Data Services"
CONFIG_MODEL=Predictive_Data_Adapter
CONFIG_MODEL_SHORT=PredictiveDataAdapter
CONFIG_MODEL_DISPLAY="Predictive Data Adapter"
CONFIG_PRODUCT=PredictiveDataAdapter
CONFIG_PRODUCT_SHORT=PDA
CONFIG_PRODUCT_LOW=pda
CONFIG_PRODUCT_DISPLAY="Predictive Data Adapter"
